# Generated by Django 4.2.14 on 2024-08-12 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("details", models.TextField(blank=True, null=True)),
                (
                    "face_image",
                    models.ImageField(blank=True, null=True, upload_to="face_images/"),
                ),
                ("face_encoding", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomerVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("is_member", models.BooleanField(default=False)),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.member",
                    ),
                ),
            ],
        ),
    ]
