# Generated by Django 4.2.14 on 2024-08-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15)),
                ("details", models.TextField(blank=True, null=True)),
                ("face_image", models.ImageField(upload_to="face_images/")),
                ("face_encoding", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
