# Generated by Django 4.2.14 on 2024-08-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="face_image",
            field=models.ImageField(blank=True, null=True, upload_to="face_images/"),
        ),
    ]
